version: "3.8"

services:
  dns_update:
    image: "dreamhost-dns-updater"
    restart: unless-stopped
    environment:
      - SCHEDULE="@hourly"
      - DREAMHOST_UPDATE_DOMAIN="node.gmail.com"
      - DREAMHOST_API_KEY="key"
